idf_component_register(
    SRCS
        "app_main.cpp"
        "ui/theme_v3.cpp"
        "ui/expressions.cpp"
        "ui/wifi_config.cpp"
        "ui/font_zh_14.c"
        # "ui/screenshot.c"  # 暂时禁用截图
        "ui/qrcode.c"
        "ui/boot_anim.c"
        "ui/radial_menu.c"
        "ui/boot_anim.c"
        "ui/dialog_bubble.c"
        "ui/audio_feedback.cpp"
        "ui/robot_memory.c"
        "ui/motion_controller.cpp"
    INCLUDE_DIRS
        "."
        "ui"
    REQUIRES
        "lvgl"
        "m5unified"
        "driver"
        "esp_wifi"
        "esp_event"
        "esp_netif"
        "esp_http_server"
)
