// xb_icons_stub.c — placeholder for the icon registry.
// The full registry is generated by tools/svg_to_lvgl.py from assets/icons/*.svg.
// Until then we use LV_SYMBOL_* fonts at the call sites; this stub keeps the
// link line stable.
#include "lvgl.h"

const void* xb_icon_get(const char* name) {
    (void)name;
    return NULL;     // call sites must fall back to LV_SYMBOL_*
}
